- name: ActiveDirectory
  hosts: ActiveDirectory
  become: false
  gather_facts: false
  roles:
    - delete_ad_user
- name: VPN
  hosts: vpn_server
  roles:
    - delete_vpn_user
- name: EJBCA Dot1X
  hosts: ejbca_dot1x
  roles:
    - delete_dot1x_user
